### PR TITLE
setActiveSheet WIP

### PR DESCRIPTION
**Pull request by ycphs**

### CODE REVIEW

**Comment by cwolcott** [comment]
This looks great. I really appreciate it.

**Comment by ycphs** [comment]
@cwolcott could you please check if your requested features works as expected?

**Comment by cwolcott** [comment]
Will do, just trying to determine how to pull a branch into RStudio to test out the changes.

**Comment by cwolcott** [comment]
Trying to use githubinstall("openxlsx"), but it is not finding the user **ycphs**.  It only suggests **awalker89**.

I was reading the following to try to load branches into RStudio
[A Helpful Way to Install R Packages Hosted on GitHub](https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html)

**Comment by cwolcott** [comment]
Ok, got it.  I used:
install_github("ycphs/openxlsx", ref="6017d25")

Will let you know soon.

**Comment by ycphs** [comment]
```
install_github("ycphs/openxlsx#169")
```

**Comment by cwolcott** [comment]
There is an issue.  When I set the activeSheet(wb) <-4 or activeSheet(wb) <- 'Configuration' the worksheet is highlighted, but so is the 1st worksheet.
Screen Shot 2021-04-06 at 2 25 51 PM

This sounds very similar to the issue mentioned in  #102.

**Comment by ycphs** [comment]
Thank you for the quick reply. @cwolcott 

The current update should fix the issue you reported.

**Comment by cwolcott** [comment]
I will pull the latest code and check later tonight.  Video taping high school soccer games currently.  Beautiful night on the US East coast

**Comment by cwolcott** [comment]
Looks good.  Works perfectly.

**Pull request merged**
