### PR TITLE
Updates for new release 

### PR DESCRIPTION
**Pull request by ycphs**

### CODE REVIEW

**Review by JanMarvin — COMMENTED** [review]
ups, did not realize that master was wrong 🤦

**Comment by JanMarvin** [comment]
Restored the correct version. Think we're good to go! (IMHO the pending PRs can wait.)

**Comment by JanMarvin** [comment]
We might wanna disable pkgdown for pull requests, the bot pushes everything to the live page. Therefore 4.2.5 is on the pkgdown site.

**Comment by ycphs** [comment]
@JanMarvin 

Yes that's a good idea.

**Comment by JanMarvin** [comment]
@ycphs I know you're busy and it's still a bloody pandemic, but can we please get this released until Christmas? It's been a long time in the making. Otherwise I will draft a release on github and continue with a new version number afterwards, if that's fine for you. There are still a few pull requests pending and I'd like to have some in the next release and the others are all not crucial.

**Comment by ycphs** [comment]
Yes a release before Christmas sounds good. @JanMarvin and  @jmbarbone thank you for the work in the last month. 

Should we merge the open PRs? @JanMarvin it would be great, if you could draft the release. That would make it much easier for me.

**Comment by JanMarvin** [comment]
From my point of view, master is ready to be the new release. We merge this pull request with minor changes to the NEWs and Description and we're fine. Regarding the pull requests, I'm not sure about the state of #213 . My open pull requests #291 and #297 should be merged after the release (from my point of view we are to late in the release window and they modify some of the rusty internals of openxlsx). #301 and #302 are still drafts.

**Comment by JanMarvin** [comment]
I have rebased this branch on master and pushed. Once the CI approves, it can be merged and released. Not sure if we need anything specific in the release notes, maybe copy the section from NEWS?

**Comment by JanMarvin** [comment]
Merged and created a release. I have attached the R tar file. All that remains is pushing that thing to CRAN and well the pleasure of working with their responses.

**Pull request merged**
