### PR TITLE
Remove refs to missing objects from [Content_Types].xml and xl/_rels/workbook.xml.rels

### PR DESCRIPTION
**Pull request by acobolew**
This PR to resolve issue #285--both the orig issue with broken link in [Content_Types].xml and elaboration of that issue as described in that issue's comments (broken links in xl/_rels/workbook.xml.rels )

### CODE REVIEW

**Comment by JanMarvin** [comment]
Looks like `writeDataTable()` needs some way to add drawings and possibly `removeTable()` a way to remove drawings from content_types. It's a can of worms

**Comment by acobolew** [comment]
@JanMarvin Thank you, I didn't understand the error messages without guidance, but your explanation provides a nice guide to get me started. I haven't examined the test suite (but will), but I do note that when I create an empty Excel file in Windows (right-click from Explorer to create an empty xlsx file), the [Content_Types].xml is definitely missing the /xl/drawings/drawing1.xml reference -- but openxlsx adds it back in after loadWorkbook followed by saveWorkbook (EDIT: but I see that my fix to [Content_Types].xml actually passed all tests--it was my fix to the xl/_rels/workbook.xml.rels that failed the test suite)

I will spend some time with the test suite.

At this point, until I nail this down, should I push additional commits to remote-refs-to-missing-drawings-from-xml branch on acobolew/openxlsx , open a new branch on acobolew/openxlsx , or close the PR until I solve the issue?

**Comment by JanMarvin** [comment]
Hi @acobolew , the issue at hand is that `openxlsx` should keep track if there are drawings attached to sheets. This is not guaranteed and therefore we should check if we add or remove references to this. Maybe a check in `saveWorkbook()` prior to writing is sufficient.

You can mark this PR as work in progress and push to the original branch that'll update the PR too. Once our tests are fine, you should add one or two yourself.

**Comment by JanMarvin** [comment]
This was superseded by #301, therefore I close this issue. Please have a look if #301 can solve the issue or open a new pull request, if you wish to further work on the issue. Thanks

**Comment by acobolew** [comment]
> This was superseded by #301, therefore I close this issue. Please have a look if #301 can solve the issue or open a new pull request, if you wish to further work on the issue. Thanks

Nice fix. So the only Q seems to be additional testing because of a concern that wb$vml[[1]] could get clobbered?

**Comment by JanMarvin** [comment]
Yes, correct. I am not sure what is supposed to happen in `wb$vml` and it looked to me as if there might be something else inside. Maybe it is some kind of stacked xml-like tree and we need to merge it or something, but I hadn't had time to further look into it.

**Pull request closed without merging**
