### PR TITLE
unicode escape for shared strings

### PR DESCRIPTION
**Pull request by ycphs**
add and remove escape (_x005F) for format _xhhhh_

### CODE REVIEW

**Comment by ycphs** [comment]
fix for #206

**Comment by JanMarvin** [comment]
Hi @ycphs , did you figure out, what's causing this behavior in the first place? I assume it's one of of the many loops we have to jump through, to provide UTF-8?

**Comment by ycphs** [comment]
Hi @JanMarvin ,

It has nothing to do with the utf8 conversion. It's an "Excel" feature converting all strings in the format `_xhhhh_` to the unicode character, if not escaped with `_x005f`.

I just found some hints at SO like [thread](https://stackoverflow.com/questions/47515917/spreadsheetdocument-openxml-decoding-the-encoded-text-in-excel-file).

I tried to check the behaviour on libre office, but I didn't had the expected results. Any input is welcomed!

**Comment by JanMarvin** [comment]
Got it, thanks for the explanation!

**Comment by ycphs** [comment]
It seems Microsoft Excel has the issue, but with libreoffice calc the encoding issue doesn't exist

**Comment by ycphs** [comment]
I have to find a way to get the standard app for .xlsx files. Based on that an additional option could be set. 

Basically Microsoft Excel with the strange escape and others like libre office without the escape. This impacts the read and the write functions.

**Comment by JanMarvin** [comment]
iirc there are additional sheet names in app.xml. maybe these are used too? and even though it's possible, is it really worth the hassle? if the user can circumvent it, shouldn't we just document it and leave it be? otherwise maybe someone can provide an xlsx file that behaves identical in Excel and Libreoffice?

**Comment by JanMarvin** [comment]
Something like this should do the trick. The regex is from [Microsoft](https://github.com/dotnet/wcf/blob/1a291ea424991a184ffafd2ba20928e0e339fb96/src/dotnet-svcutil/lib/src/FrameworkFork/Microsoft.Xml/Xml/XmlConvert.cs#L212) and apparently it checks for strings that look like unicode chars utf-16 and utf-32. The entire idea seems to be, that it guards against unwanted unicode conversion.
```R

string <- "_topic_ext_xb025_tm" #original issue
string <- "_topic_ext_Xb0288886_tm" # test with 8 chars after _x
expr <- "(?<=_)[Xx]([0-9a-fA-F]{4}|[0-9a-fA-F]{8})_"

# convert to matrix n x 2
get <- matrix(unlist(stringi::stri_match_all_regex(pattern = expr, str = string)), ncol=2)

# add unicode _ as prefix ("x005F")
get[,2] <- paste0("x005F_x", get[,2], "_")

# replace in string
stringi::stri_replace_all_fixed(string, pattern = get[,1], replacement = get[,2], vectorize_all = F)
```

Didn't test the impact in Excel or LibreOffice, but with .NETs `XmlConvert.EncodeName` [here](https://dotnetfiddle.net/eEFrCs). The actual EncodeName code is not only the regex, but I didn't try to understand the EncodeName code :smile: (apparently it encodes other cases as well: e.g. if the name begins with a number, the first digit is encoded into its unicode representation 1 becomes `_x0031` and other signs notably `>` is converted too; see also `Unicode::as.u_char(utf8ToInt("_"))`)

**Comment by ycphs** [comment]
#152

**Pull request closed without merging**
