### PR TITLE
fix active worksheet after worksheetorder changes

### PR DESCRIPTION
**Pull request by ycphs**

### CODE REVIEW

**Comment by cwolcott** [comment]
Still having issues after installing the pull request
This is what the excel spreadsheet looks like after creating it.
PullRequest171 v01

This is what it looks like after performing **worksheetOrder(wb) <- c(4, 1, 2, 3)**
Moving the Configuration tab to the front.  I would have expected that the MeanTemp tab would still be the only active tab.
PullRequest171 v02

**Comment by cwolcott** [comment]
This commit fails when I load it with the following:
Error in parse(outFile) : 
  /private/var/folders/k2/jnzs4kkd47v5bgccw3_kwf_08_6qz4/T/Rtmp5VseD9/R.INSTALLd9d81255177f/openxlsx/R/WorkbookClass.R:3301:5: unexpected 'if'
3300: 
3301:     if

**Comment by ycphs** [comment]
thank you for checking. I just forgot to comment one bracket. 

with LibreOffice the selection of the active sheet works, but currently I can't check with Microsoft Office. I am looking forward to hearing your feedback.

**Comment by cwolcott** [comment]
Will. Heck later tonight after high soccer.

**Comment by cwolcott** [comment]
Pulled in the latest code via **install_github("ycphs/openxlsx#&#8203;171")** this morning.
Still looks the same as the previous [execution](https://github.com/ycphs/openxlsx/pull/171#issuecomment-816791909).
Screen Shot 2021-04-14 at 7 38 52 AM

**Comment by ycphs** [comment]
@cwolcott could you please provide one file showing the error and one with the target situation.

**Comment by cwolcott** [comment]
@ycphs Is this what you are looking for?

Here is my code, just uncomment the worksheetOrder.
Also attached are to two resulting spreadsheets.
[openxlsx.pr171.base.xlsx](https://github.com/ycphs/openxlsx/files/6312756/openxlsx.pr171.base.xlsx)
[openxlsx.pr171.worksheetorder.xlsx](https://github.com/ycphs/openxlsx/files/6312757/openxlsx.pr171.worksheetorder.xlsx)

```
library(openxlsx)

wb <- createWorkbook()
addWorksheet(wb, 'A1')
addWorksheet(wb, 'B2')
addWorksheet(wb, 'C3')
addWorksheet(wb, 'D4')

# Pull Request #171
#worksheetOrder(wb) <- c(4, 1, 2, 3)

xlsxFile <- file.path(path.expand("~"),'temp', 'openxlsx.pr171.xlsx')
saveWorkbook(wb, xlsxFile, overwrite=TRUE)
```
**Without** the worksheetOrder(wb) <- c(4, 1, 2, 3)
openxlsx pr171 base
**With** worksheetOrder(wb) <- c(4, 1, 2, 3)
openxlsx pr171 worksheetorder

**Comment by ycphs** [comment]
Yes that is what I am looking for. Thank you @cwolcott 

I checked it on libreoffice and it worked, but now I am able to check on ms office.

**Comment by ycphs** [comment]
It seems that the method `worksheetOrder` in the workbook class has an issue, with handling correcting the selected sheet. 

I will take a look into it. Maybe it is necessary to set the active sheet after during the call of the method `worksheetOrder`.

**Comment by cwolcott** [comment]
That doesn't seem to work either.  Here is the result of setting the activeSheet after worksheetOrder.
```
library(openxlsx)

wb <- createWorkbook()
addWorksheet(wb, 'A1')
addWorksheet(wb, 'B2')
addWorksheet(wb, 'C3')
addWorksheet(wb, 'D4')

# Pull Request #171
worksheetOrder(wb) <- c(4, 1, 2, 3)
activeSheet(wb) <- 'D4'

xlsxFile <- file.path(path.expand("~"),'temp', 'openxlsx.pr171.xlsx')
saveWorkbook(wb, xlsxFile, overwrite=TRUE)
```

openxlsx pr171 worksheetorder activeSheet

**Comment by cwolcott** [comment]
Loaded new commit, but still have the same  first and last tabs active.

**Comment by cwolcott** [comment]
The changes fixed everything, thank you.

Are you considering pushing a new release soon with all your recent fixes and improvement, since 4.2.3 is from last October?

**Comment by ycphs** [comment]
Yes, a new release is definitely necessary to have all the new features available also in the package on CRAN.

Thank you for your patience and your efforts in testing.

**Pull request merged**
