### PR TITLE
Add hexagon badge

### PR DESCRIPTION
**Pull request by christiankaindl**
While developing our "R for Excel Users" course at Quantargo we noticed that openxlsx doesn't have a hexagon badge yet. So we thought we'd help and contribute one, this is what it looks like:

badge_openxslx(1)

The pull request also contains an SVG version, and also adds the badge to the project Readme. The colors are directly inspired by the latest [Excel logo](https://en.wikipedia.org/wiki/Microsoft_Excel#/media/File:Microsoft_Office_Excel_(2018%E2%80%93present).svg) from Microsoft.

Let us know what you think! :)

CC @mannau

### CODE REVIEW

**Comment by JanMarvin** [comment]
is this a generous offer to advertise for you? 😉

**Comment by mannau** [comment]
Just a generous offer - as discussed with @ycphs 

@christiankaindl : pls remove the quantargo line from the logo.

**Comment by christiankaindl** [comment]
Sure! Removed the Quantargo line and updated the pull request

**Comment by ycphs** [comment]
Thank you for your contribution @christiankaindl, @mannau 

@christiankaindl thank you for the changes stimulated by @JanMarvin.

**Pull request merged**
