### PR TITLE
#86 add Delete/Overwrite named regions functionality

### PR DESCRIPTION
**Pull request by bthieurmel**
Add : 

- new parameter ``overwrite = FALSE`` in ``createNameRegions``
- and new function ``deleteNameRegions``

### CODE REVIEW

**Comment by bthieurmel** [comment]
Really not so must change, only few lines (not 600 as git say...!)

image

image

+ doc

**Comment by ycphs** [comment]
I thought of implementing also the printing region. And also a check if the named region overwrites it.

**Comment by ycphs** [comment]
Feature request for editing the print area 

#235

**Comment by ycphs** [comment]
> Really not so must change, only few lines (not 600 as git say...!)
> 
> image
> 
> image
> 
> * doc

Could you please create a new PR without the white space changes.

**Comment by bthieurmel** [comment]
Yes. PR without space here #251

**Pull request closed without merging**
