### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by wleoncio**
Minor change involving a text correction plus some whitespace removal automatically done by my IDE and Roxygen version update done by `devtools::check()`.

- Fixed typo
- (Automatic) whitespace removal

### CODE REVIEW

**Comment by wleoncio** [comment]
You're probably already aware of this, but for the record, the codecov failure is probably caused by failing tests which are unrelated to this PR; they happen in the "error without write permissions" context. BTW, the following unit tests also need some work due to being empty (contexts "Images and Tables.", "Re-ordering worksheets." and "Write zero rows & columns". Has this been reported (couldn't find it anywhere)? Is anyone working on it?

**Comment by JanMarvin** [comment]
Hi @wleoncio , thanks for the pull request. We are aware of the failing covr check and it is no issue. Regarding development, @jmbarbone and I have moved on to `openxlsx2` and @ycphs lately has other things to take care of. Therefore there is not really development here, just maintenance.

PS: *sigh* all these unrelated whitespace changes, they are not an issue and I consider it a bad habit of Rstudio users to include these changes into every pull request.

**Comment by wleoncio** [comment]
Fair enough, I can work around the issue on my code with a `suppressWarnings()` wrap.

> PS: _sigh_ all these unrelated whitespace changes, they are not an issue and I consider it a bad habit of Rstudio users to include these changes into every pull request.

Does this mean those of us on other editors get a free pass? 😛  Seriously, though, I agree that a commit for whitespace removal adds unwanted noise, but I wonder why the linter didn't catch those before they made it into the repo.

**Comment by JanMarvin** [comment]
I'll take a look at both PRs once I'm home and will merge them to development, but I have no idea when they will be on CRAN or the main branch here on GitHub. Therefore unless you depend on CRAN most likely you won't need to add the suppression.

Most of the code is six to eight years old at this point and I assume and not everyone of us is that short on disk space that a few whitespaces matter much ;)

Nevertheless: Thanks for the contribution! We all have just a limited amount of time and every bit helps. (I once started my endeavor to open source software with a major whitespace cleanup, almost two decades ago, today I would lecture myself 😄 )

**Comment by jmbarbone** [comment]
> PS: _sigh_ all these unrelated whitespace changes, they are not an issue and I consider it a bad habit of Rstudio users to include these changes into every pull request.

You can always hide whitespace in [diffs online](https://github.blog/changelog/2021-10-14-hiding-whitespace-is-now-remembered-for-each-pull-request/) or [in the desktop app](https://github.blog/2021-04-28-github-desktop-hiding-whitespace-expanding-diffs-repo-aliases/).

**Review by JanMarvin — APPROVED** [review]

**Comment by JanMarvin** [comment]
Thanks, merged!

**Pull request merged**
