### PR TITLE
Preserve window size and position, also get and set

### PR DESCRIPTION
**Pull request by michael-dewar**
This PR will preserve the size and position of the window when you open the xlsx in Excel. There are also functions to set and get directly.

I had earlier created a PR #383, but it got hopelessly out-of-date with the changes to the package.  I closed that old PR and created this new one.  My hope is that this will allow a cleaner merge, assuming people find this PR useful.

### CODE REVIEW

**Comment by epruesse** [comment]
@JanMarvin What would it take to get this merged? It's been on my wish list for a while. I too had a patch for this, just a bit more simplistic. I'm willing to work on this if @michael-dewar has no time and you've got specific criteria that would make the PR acceptable.

**Comment by JanMarvin** [comment]
Hi @epruesse , honestly, I have no intention to lead the development of `openxlsx`. I only took over maintenance as a favor to CRAN, @ycphs and to the many packages that depend on `openxlsx`, when CRAN was considering to archive `openxlsx`. I've been busy the last years developing `openxlsx2` and my time and energy resources are limited.

As a last resort, if you can both agree that whatever is in this PR works with R and spreadsheet software and can confirm that you have tested things and it is in a merge-able state, lean as in not touching dozens of places, covered by tests, and nothing breaks - I'll be willing to merge it.

**Comment by michael-dewar** [comment]
Hello @JanMarvin , thank you very much for taking over the maintenance of this project.  

1. I have made the PR mergeable by bringing it up to date with the changes to the master branch of ycphs since I made the PR.  The commit history above looks long, but most of those are from when I brought my branch up to date.  My changes are only contained in four commits from April 19, 2024.
2. The code changes are very lean.  They only touch the bare minimum in order to preserve and set the window size.  I do not change other code.
3. The new functions are documented.
4. The new code has tests in a file called `test-setWindowSize.R`.  All of the new and old tests pass without issue.
5. `devtools::check()` has no issues.
6. I have built the package in both Windows 11 and macOS Sonoma 14.5.  I am able to use the new features to read and write `xlsx` files and the window size and position features work as expected when I open the files in Excel for Mac.  When I open them in Excel for Windows 11, the window size and position feature appeared to have no effect.  But at least they were not corrupted or anything.  I can also open the files correctly in the web version of Excel and in Numbers for Mac, although the windows size features are not relevant there.

@epruesse , are you able to test the feature on Windows?

**Comment by epruesse** [comment]
I don't use windows myself, but I may be able to find someone, at least to check the resulting files.

**Comment by JanMarvin** [comment]
Can you please rebase the PR? It’s currently touching 47 files, including GitHub workflows, which is not lean at all 😉

**Comment by michael-dewar** [comment]
I can create a new PR, but I am unable to rebase this one.  I originally tried to rebase it, but my git skills were not up to the task.

**Comment by JanMarvin** [comment]
Thanks, understandable - git can be challenging, but that would be lovely! Please try to reduce the changes to the minimum.

**Comment by michael-dewar** [comment]
@JanMarvin @epruesse I have created a clean PR from a rebased branch.  Please see PR #487 .  Thanks.

**Pull request closed without merging**
