### PR TITLE
Add type blanks and not blanks to conditional formatting. fixes #179

### LINKED ISSUE #179: Request: Add type 'blank' to conditionalFormatting
**Is your feature request related to a problem? Please describe.**
I would like to be able to set conditional formatting to blank cells

**Describe the solution you'd like**
Add a new type "blank" to conditionalFormatting parameter

**Describe alternatives you've considered**
Instead of blank I am currently setting the cell to '---' and using the conditionalFormatting type="contains" rule="---"

**Additional context**

conditionalFormatting blanks rules
conditionalFormatting blanks edit

### PR DESCRIPTION
**Pull request by vkatti**
Addresses Issue #179 

1. Added new type='blanks' and type='notBlanks' in the conditionalFormatting function.
2. Added 3 tests for same.

### CODE REVIEW

**Comment by vkatti** [comment]
Hi @ycphs, I am not sure what do I need to do to fix the failing checks for macOS. Request your guidance. Thanks.

My session info is as follows:
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.2.5

loaded via a namespace (and not attached):
 [1] zip_2.2.0         Rcpp_1.0.7        pillar_1.6.4      compiler_4.1.0   
 [5] prettyunits_1.1.1 remotes_2.4.2     tools_4.1.0       digest_0.6.29    
 [9] testthat_3.1.1    pkgbuild_1.3.1    pkgload_1.2.4     memoise_2.0.1    
[13] lifecycle_1.0.1   tibble_3.1.6      pkgconfig_2.0.3   rlang_0.4.12     
[17] cli_3.1.0         rstudioapi_0.13   commonmark_1.7    curl_4.3.2       
[21] xopen_1.0.0       xfun_0.29         fastmap_1.1.0     withr_2.4.3      
[25] stringr_1.4.0     roxygen2_7.1.2    knitr_1.37        xml2_1.3.3       
[29] desc_1.4.0        fs_1.5.2          vctrs_0.3.8       devtools_2.4.3   
[33] rprojroot_2.0.2   glue_1.6.0        R6_2.5.1          processx_3.5.2   
[37] fansi_0.5.0       rcmdcheck_1.4.0   sessioninfo_1.2.2 callr_3.7.0      
[41] purrr_0.3.4       magrittr_2.0.1    codetools_0.2-18  ps_1.6.0         
[45] ellipsis_0.3.2    usethis_2.1.5     utf8_1.2.2        stringi_1.7.6    
[49] cachem_1.0.6      crayon_1.4.2

**Comment by JanMarvin** [comment]
Hi @vkatti , don't worry. Apparently this test fails Mac. Maybe they don't allow internet access anymore. We can try to disable it if internet access is not available. It's not all that important.

https://github.com/ycphs/openxlsx/blob/5e44c5e9b6885800eca4b8a608c0439919f2ec8c/tests/testthat/test-read_sources.R#L13

**Comment by vkatti** [comment]
Oh OK. So... is there anything I need to do further?

**Comment by JanMarvin** [comment]
No, nothing to do right now. Just wait until someone can review the pull request. Thanks for the pull request!

**Comment by JanMarvin** [comment]
Thank you for your contribution!

**Pull request merged**
